name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        kernel_version:
          - master
          - v6.8
        kconfig_pm:
          - "-e CONFIG_PM"
          - "-d CONFIG_PM"
        kconfig_debug_fs:
          - "-e CONFIG_DEBUG_FS"
          - "-d CONFIG_DEBUG_FS"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          path: src
      - run: echo "::add-matcher::src/.github/workflows/gcc-problem-matcher.json"
      - run: sudo apt-get update
      - run: sudo apt-get install -y libelf-dev sparse
      - uses: actions/checkout@v6
        with:
          repository: torvalds/linux
          path: linux
          ref: ${{ matrix.kernel_version }}
      - run: cp src/.github/workflows/all.config linux/
      - run: scripts/config --file all.config ${{ matrix.kconfig_pm }} ${{ matrix.kconfig_debug_fs }}
        working-directory: linux
      - run: KCONFIG_ALLCONFIG=1 KCFLAGS=-Werror make C=1 allnoconfig
        working-directory: linux
      - run: KCFLAGS=-Werror make C=1 -j$(nproc)
        working-directory: linux
      - run: KCFLAGS=-Werror make C=1 -k "KDIR=${{ github.workspace }}/linux"
        working-directory: src
